DROP TABLE IF EXISTS agent_queues CASCADE;
DROP TABLE IF EXISTS queues CASCADE;
ALTER TABLE agents DROP COLUMN IF EXISTS user_id;
ALTER TABLE agents DROP COLUMN IF EXISTS languages;
ALTER TABLE agents DROP COLUMN IF EXISTS priority;
ALTER TABLE agents DROP COLUMN IF EXISTS schedule;
ALTER TABLE agents DROP COLUMN IF EXISTS customer_tiers;
ALTER TABLE agents DROP COLUMN IF EXISTS current_calls;
