apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: voiceagent
  labels:
    app: whisper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
        - name: whisper
          image: fedirz/faster-whisper-server:latest-cpu
          env:
            - name: WHISPER__MODEL
              value: "Systran/faster-whisper-base.en"
          ports:
            - containerPort: 8000
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 1Gi
